#!/bin/bash

adduser node --no-create-home --disabled-password --gecos ""
mkdir /var/run/node
mkdir /var/log/node
PT=`pwd | xargs  dirname`
cp scripts/init/monitor /etc/init.d/
sed -i "s|export BASEPATH=/opt|export BASEPATH=$PT|" /etc/init.d/monitor
chmod +x /etc/init.d/monitor
update-rc.d monitor defaults
npm install
/etc/init.d/monitor start
